//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinkyRailways.Core.State {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinkyRailways.Core.State.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set loc in automatic controlled mode without an assigned block..
        /// </summary>
        internal static string Cannot_set_loc_in_automatic_controlled_mode_without_an_assigned_block {
            get {
                return ResourceManager.GetString("Cannot_set_loc_in_automatic_controlled_mode_without_an_assigned_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock {0} -&gt; {1}.
        /// </summary>
        internal static string ClockXY {
            get {
                return ResourceManager.GetString("ClockXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of {0} failed because: {1}.
        /// </summary>
        internal static string ErrInitializationOfXFailedBecauseY {
            get {
                return ResourceManager.GetString("ErrInitializationOfXFailedBecauseY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform action.
        /// </summary>
        internal static string FailedToPerformAction {
            get {
                return ResourceManager.GetString("FailedToPerformAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0}.
        /// </summary>
        internal static string InitializingX {
            get {
                return ResourceManager.GetString("InitializingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputReport [{0}] for unknown address {1}.
        /// </summary>
        internal static string InputReportForUnknownAddress {
            get {
                return ResourceManager.GetString("InputReportForUnknownAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is not locked by this loc..
        /// </summary>
        internal static string LocBlockIsNotLockedByThisLoc {
            get {
                return ResourceManager.GetString("LocBlockIsNotLockedByThisLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reset block assignment in automatic mode.
        /// </summary>
        internal static string LocCannotResetCurrentBlockInAutomaticMode {
            get {
                return ResourceManager.GetString("LocCannotResetCurrentBlockInAutomaticMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  F.
        /// </summary>
        internal static string LocForwardPostfix {
            get {
                return ResourceManager.GetString("LocForwardPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  R.
        /// </summary>
        internal static string LocReversePostfix {
            get {
                return ResourceManager.GetString("LocReversePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing can only be set for locs that are not allowed to change direction..
        /// </summary>
        internal static string LocReversingNotAllowed {
            get {
                return ResourceManager.GetString("LocReversingNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign route ....
        /// </summary>
        internal static string LocStateAssignRoute {
            get {
                return ResourceManager.GetString("LocStateAssignRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string LocStateManual {
            get {
                return ResourceManager.GetString("LocStateManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual in {0}.
        /// </summary>
        internal static string LocStateManualInX {
            get {
                return ResourceManager.GetString("LocStateManualInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing route ....
        /// </summary>
        internal static string LocStatePreparingRoute {
            get {
                return ResourceManager.GetString("LocStatePreparingRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing.
        /// </summary>
        internal static string LocStateReversingWaitingForDirectionChange {
            get {
                return ResourceManager.GetString("LocStateReversingWaitingForDirectionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}s.
        /// </summary>
        internal static string LocStateWaitingXSeconds {
            get {
                return ResourceManager.GetString("LocStateWaitingXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} is not locked by {1}, instead it is locked by {2}.
        /// </summary>
        internal static string ObjectXNotLockedByYButByZ {
            get {
                return ResourceManager.GetString("ObjectXNotLockedByYButByZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} is not locked by {1}, instead it is not locked.
        /// </summary>
        internal static string ObjectXNotLockedByYNotLocked {
            get {
                return ResourceManager.GetString("ObjectXNotLockedByYNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output {0} -&gt; {1}.
        /// </summary>
        internal static string OutputStateXY {
            get {
                return ResourceManager.GetString("OutputStateXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string RouteClosed {
            get {
                return ResourceManager.GetString("RouteClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical section is occupied.
        /// </summary>
        internal static string RouteCriticalSectionOccupied {
            get {
                return ResourceManager.GetString("RouteCriticalSectionOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will cause deadlock.
        /// </summary>
        internal static string RouteDeadLock {
            get {
                return ResourceManager.GetString("RouteDeadLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination block closed.
        /// </summary>
        internal static string RouteDestinationClosed {
            get {
                return ResourceManager.GetString("RouteDestinationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of direction not allowed.
        /// </summary>
        internal static string RouteDirectionChangeNeeded {
            get {
                return ResourceManager.GetString("RouteDirectionChangeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by {0}.
        /// </summary>
        internal static string RouteLockedX {
            get {
                return ResourceManager.GetString("RouteLockedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission.
        /// </summary>
        internal static string RouteNoPermission {
            get {
                return ResourceManager.GetString("RouteNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposing traffic in {1}.
        /// </summary>
        internal static string RouteOpposingTrafficInX {
            get {
                return ResourceManager.GetString("RouteOpposingTrafficInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible.
        /// </summary>
        internal static string RoutePossible {
            get {
                return ResourceManager.GetString("RoutePossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor(s) active.
        /// </summary>
        internal static string RouteSensorActive {
            get {
                return ResourceManager.GetString("RouteSensorActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor {0} -&gt; {1}.
        /// </summary>
        internal static string SensorXStateToY {
            get {
                return ResourceManager.GetString("SensorXStateToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchReport [{0}] for unknown address {1}.
        /// </summary>
        internal static string SwitchReportForUnknownAddress {
            get {
                return ResourceManager.GetString("SwitchReportForUnknownAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual command station.
        /// </summary>
        internal static string VirtualCommandStationDescription {
            get {
                return ResourceManager.GetString("VirtualCommandStationDescription", resourceCulture);
            }
        }
    }
}
