{
 "title": "Local Workers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "local_worker_id", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "I2C Executions [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(binkyrailways_bridge_i2c_execute_total{job=~\"$local_worker_id\"}[1m])",
     "legendFormat": "{{job}}-{{address}}"
    }
   ]
  },
  {
   "title": "I2C Failed Executions [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(binkyrailways_bridge_i2c_execute_error_total{job=~\"$local_worker_id\"}[1m])",
     "legendFormat": "{{job}}-{{address}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "binkyrailways_devices_devices_created_total{job=~\"$local_worker_id\"}",
     "legendFormat": "{{job}}-created"
    },
    {
     "expr": "binkyrailways_devices_devices_configured_total{job=~\"$local_worker_id\"}",
     "legendFormat": "{{job}}-configured"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "binkyrailways_objects_objects_created_total{job=~\"$local_worker_id\"}",
     "legendFormat": "{{job}}-created"
    },
    {
     "expr": "binkyrailways_objects_objects_configured_total{job=~\"$local_worker_id\"}",
     "legendFormat": "{{job}}-configured"
    }
   ]
  }
 ]
}