{
 "title": "Sensors",
 "time": { "from": "2023-03-04T11:27:33.159Z", "to": "2023-03-04T12:01:52.303Z" },
 "panels": [
  { "title": "Sensor data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "binkyrailways_objects_binary_sensor_actual",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Sensor changes [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(binkyrailways_objects_binary_sensor_changes_total[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Sensor read errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "binkyrailways_objects_binary_sensor_read_errors_total",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}