{
 "title": "Switch behavior",
 "time": { "from": "2023-02-19T12:33:49.812Z", "to": "2023-02-19T14:00:11.787Z" },
 "templating": {
  "list": [
   {
    "name": "switch_id",
    "label": "Switch ID",
    "query": {
     "query": "binkynetmanager_manager_switch_pool_set_request_total"
    }
   }
  ]
 },
 "panels": [
  { "title": "BinkyRailways API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switch Set Actual [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(binkynetmanager_service_switch_set_actual_total{address=~\"$switch_id\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Switch Watch Request Messages [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(binkynetmanager_service_switch_watch_request_messages_total{address=~\"$switch_id\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "NetManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Set switch actual [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "increase(binkynetmanager_manager_switch_pool_set_actual_total{address=~\"$switch_id\"}[1m])",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Set switch request [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "increase(binkynetmanager_manager_switch_pool_set_request_total{address=~\"$switch_id\"}[1m])",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Switch pool SubActual messages [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "increase(binkynetmanager_manager_switch_pool_sub_actual_messages_total{address=~\"$switch_id\"}[1m])",
       "legendFormat": "{{address}}"
      },
      {
       "expr": "increase(binkynetmanager_manager_switch_pool_sub_actual_messages_failed_total{address=~\"$switch_id\"}[1m])",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Switch pool SubRequest messages [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "increase(binkynetmanager_manager_switch_pool_sub_request_messages_total[1m])",
       "legendFormat": "{{address}}"
      },
      {
       "expr": "increase(binkynetmanager_manager_switch_pool_sub_request_messages_failed_total[1m])",
       "legendFormat": "{{address}}"
      }
     ]
    }
   ]
  },
  { "title": "Local worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Switch direction requests received by LWs [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(binkyrailways_objects_switch_direction_requests_total{id=~\"$switch_id\"}[5m])",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}