// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: br_app_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("br_app_service.proto", fileDescriptor_759ad9a3938c040a) }

var fileDescriptor_759ad9a3938c040a = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2a, 0x8a, 0x4f,
	0x2c, 0x28, 0x88, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x12, 0x48, 0xca, 0xcc, 0xcb, 0xae, 0x2c, 0x4a, 0xcc, 0xcc, 0x29, 0x4f, 0xac, 0x2c, 0xd6,
	0x2b, 0x33, 0x94, 0x12, 0x82, 0xaa, 0x2b, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0xa8, 0x92, 0x02, 0xe9,
	0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x41, 0x16, 0x35, 0xf2, 0xe3, 0xe2, 0x72, 0x2c, 0x28, 0x08, 0x86,
	0x98, 0x27, 0xe4, 0xc0, 0xc5, 0xe5, 0x9e, 0x5a, 0xe2, 0x58, 0x50, 0xe0, 0x99, 0x97, 0x96, 0x2f,
	0x24, 0xae, 0x87, 0x6e, 0xb0, 0x9e, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x94, 0x24, 0xa6, 0x04, 0x54,
	0x8f, 0x93, 0xf3, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38,
	0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x61, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae,
	0x3e, 0x8a, 0x36, 0x7d, 0x27, 0x10, 0x2f, 0x08, 0xc6, 0x2b, 0xc8, 0x4e, 0xd7, 0x4f, 0x2c, 0xc8,
	0xd4, 0x2f, 0x33, 0x4c, 0x62, 0x03, 0xbb, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x7a,
	0x6d, 0xf8, 0xef, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppServiceClient interface {
	// Gets basic application info.
	GetAppInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppInfo, error)
}

type appServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppServiceClient(cc *grpc.ClientConn) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) GetAppInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppInfo, error) {
	out := new(AppInfo)
	err := c.cc.Invoke(ctx, "/binkyrailways.v1.AppService/GetAppInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
type AppServiceServer interface {
	// Gets basic application info.
	GetAppInfo(context.Context, *Empty) (*AppInfo, error)
}

// UnimplementedAppServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAppServiceServer struct {
}

func (*UnimplementedAppServiceServer) GetAppInfo(ctx context.Context, req *Empty) (*AppInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppInfo not implemented")
}

func RegisterAppServiceServer(s *grpc.Server, srv AppServiceServer) {
	s.RegisterService(&_AppService_serviceDesc, srv)
}

func _AppService_GetAppInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/binkyrailways.v1.AppService/GetAppInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "binkyrailways.v1.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppInfo",
			Handler:    _AppService_GetAppInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "br_app_service.proto",
}
