// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: br_state_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request arguments for EnableRunMode.
type EnableRunModeRequest struct {
	// If set, run in virtual mode, otherwise live mode.
	Virtual              bool     `protobuf:"varint,1,opt,name=virtual,proto3" json:"virtual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableRunModeRequest) Reset()         { *m = EnableRunModeRequest{} }
func (m *EnableRunModeRequest) String() string { return proto.CompactTextString(m) }
func (*EnableRunModeRequest) ProtoMessage()    {}
func (*EnableRunModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a476a990e66ccc93, []int{0}
}
func (m *EnableRunModeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnableRunModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EnableRunModeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EnableRunModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableRunModeRequest.Merge(m, src)
}
func (m *EnableRunModeRequest) XXX_Size() int {
	return m.Size()
}
func (m *EnableRunModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableRunModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableRunModeRequest proto.InternalMessageInfo

func (m *EnableRunModeRequest) GetVirtual() bool {
	if m != nil {
		return m.Virtual
	}
	return false
}

// Request arguments for GetStateChanges.
type GetStateChangesRequest struct {
	// If set, all state objects will be send to the stream before state changes
	// are passed.
	Bootstrap            bool     `protobuf:"varint,1,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateChangesRequest) Reset()         { *m = GetStateChangesRequest{} }
func (m *GetStateChangesRequest) String() string { return proto.CompactTextString(m) }
func (*GetStateChangesRequest) ProtoMessage()    {}
func (*GetStateChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a476a990e66ccc93, []int{1}
}
func (m *GetStateChangesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetStateChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetStateChangesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetStateChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateChangesRequest.Merge(m, src)
}
func (m *GetStateChangesRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetStateChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateChangesRequest proto.InternalMessageInfo

func (m *GetStateChangesRequest) GetBootstrap() bool {
	if m != nil {
		return m.Bootstrap
	}
	return false
}

// State change of a single object.
// Only one of the fields is set;
type StateChange struct {
	Railway              *RailwayState `protobuf:"bytes,1,opt,name=railway,proto3" json:"railway,omitempty"`
	Block                *BlockState   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Loc                  *LocState     `protobuf:"bytes,3,opt,name=loc,proto3" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StateChange) Reset()         { *m = StateChange{} }
func (m *StateChange) String() string { return proto.CompactTextString(m) }
func (*StateChange) ProtoMessage()    {}
func (*StateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a476a990e66ccc93, []int{2}
}
func (m *StateChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StateChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChange.Merge(m, src)
}
func (m *StateChange) XXX_Size() int {
	return m.Size()
}
func (m *StateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChange.DiscardUnknown(m)
}

var xxx_messageInfo_StateChange proto.InternalMessageInfo

func (m *StateChange) GetRailway() *RailwayState {
	if m != nil {
		return m.Railway
	}
	return nil
}

func (m *StateChange) GetBlock() *BlockState {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *StateChange) GetLoc() *LocState {
	if m != nil {
		return m.Loc
	}
	return nil
}

type SetPowerRequest struct {
	// Is set, power will be turned on, otherwise power will be turned off.
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPowerRequest) Reset()         { *m = SetPowerRequest{} }
func (m *SetPowerRequest) String() string { return proto.CompactTextString(m) }
func (*SetPowerRequest) ProtoMessage()    {}
func (*SetPowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a476a990e66ccc93, []int{3}
}
func (m *SetPowerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetPowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetPowerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetPowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPowerRequest.Merge(m, src)
}
func (m *SetPowerRequest) XXX_Size() int {
	return m.Size()
}
func (m *SetPowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPowerRequest proto.InternalMessageInfo

func (m *SetPowerRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*EnableRunModeRequest)(nil), "binkyrailways.v1.EnableRunModeRequest")
	proto.RegisterType((*GetStateChangesRequest)(nil), "binkyrailways.v1.GetStateChangesRequest")
	proto.RegisterType((*StateChange)(nil), "binkyrailways.v1.StateChange")
	proto.RegisterType((*SetPowerRequest)(nil), "binkyrailways.v1.SetPowerRequest")
}

func init() { proto.RegisterFile("br_state_service.proto", fileDescriptor_a476a990e66ccc93) }

var fileDescriptor_a476a990e66ccc93 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x5d, 0x4a, 0xeb, 0x40,
	0x14, 0x80, 0x6f, 0x6e, 0xb9, 0xb7, 0x75, 0xaa, 0x56, 0x86, 0x52, 0x43, 0xa8, 0x41, 0xf3, 0x20,
	0x05, 0x25, 0x69, 0x2b, 0x88, 0xcf, 0xad, 0xa5, 0x28, 0x16, 0x24, 0x7d, 0x10, 0x44, 0x28, 0x93,
	0x74, 0x68, 0x43, 0xd3, 0x4c, 0xcc, 0x4c, 0x52, 0xb2, 0x13, 0xb7, 0x20, 0x6e, 0xc4, 0x47, 0x97,
	0x20, 0x75, 0x23, 0x92, 0x49, 0xa3, 0xa9, 0x09, 0x14, 0x7c, 0xcb, 0x99, 0x7c, 0xdf, 0xc9, 0xf9,
	0x99, 0x80, 0x9a, 0xe1, 0x8d, 0x28, 0x43, 0x0c, 0x8f, 0x28, 0xf6, 0x02, 0xcb, 0xc4, 0xaa, 0xeb,
	0x11, 0x46, 0xe0, 0x9e, 0x61, 0x39, 0xb3, 0xd0, 0x43, 0x96, 0xbd, 0x40, 0x21, 0x55, 0x83, 0x96,
	0x54, 0xfd, 0x22, 0x59, 0xe8, 0x62, 0x1a, 0x73, 0xfc, 0x74, 0x4e, 0xc6, 0xd8, 0x4e, 0x9f, 0x2a,
	0x4d, 0x50, 0xed, 0x39, 0xc8, 0xb0, 0xb1, 0xee, 0x3b, 0x03, 0x32, 0xc6, 0x3a, 0x7e, 0xf4, 0x31,
	0x65, 0x50, 0x04, 0xc5, 0xc0, 0xf2, 0x98, 0x8f, 0x6c, 0x51, 0x38, 0x14, 0x1a, 0x25, 0x3d, 0x09,
	0x95, 0x73, 0x50, 0xeb, 0x63, 0x36, 0x8c, 0xf2, 0x77, 0xa7, 0xc8, 0x99, 0x60, 0x9a, 0x38, 0x75,
	0xb0, 0x65, 0x10, 0xc2, 0x28, 0xf3, 0x90, 0xbb, 0xb2, 0xbe, 0x0f, 0x94, 0x67, 0x01, 0x94, 0x53,
	0x16, 0xbc, 0x00, 0xc5, 0x55, 0xd1, 0x9c, 0x2d, 0xb7, 0x65, 0xf5, 0x67, 0x27, 0xaa, 0x1e, 0x3f,
	0x73, 0x4d, 0x4f, 0x70, 0xd8, 0x06, 0xff, 0x0c, 0x9b, 0x98, 0x33, 0xf1, 0x2f, 0xf7, 0xea, 0x59,
	0xaf, 0x13, 0xbd, 0x8e, 0xad, 0x18, 0x85, 0xa7, 0xa0, 0x60, 0x13, 0x53, 0x2c, 0x70, 0x43, 0xca,
	0x1a, 0x37, 0xc4, 0x8c, 0xf9, 0x08, 0x53, 0x4e, 0x40, 0x65, 0x88, 0xd9, 0x2d, 0x59, 0x60, 0x2f,
	0x35, 0x10, 0xcc, 0x07, 0x35, 0x4e, 0x06, 0xb2, 0x0a, 0xdb, 0x2f, 0x05, 0xb0, 0xcd, 0xdd, 0x61,
	0xbc, 0x17, 0x78, 0x0d, 0x2a, 0x7d, 0xcc, 0xd2, 0xb5, 0xc3, 0xfd, 0xec, 0x17, 0x7b, 0x73, 0x97,
	0x85, 0xd2, 0x86, 0xa6, 0xe1, 0x1d, 0xd8, 0x59, 0xdb, 0x0f, 0x3c, 0xce, 0xc9, 0x94, 0xb3, 0xc0,
	0x8d, 0x89, 0xaf, 0xc0, 0xee, 0xa5, 0x45, 0xd3, 0x99, 0x7f, 0x5d, 0xe3, 0x03, 0xef, 0x37, 0x7d,
	0x23, 0x60, 0x23, 0xab, 0xe4, 0x5f, 0x1a, 0xe9, 0x20, 0x4b, 0xa6, 0xb0, 0xa6, 0x00, 0x07, 0xa0,
	0x94, 0xec, 0x02, 0x1e, 0xe5, 0xc0, 0xeb, 0x7b, 0xda, 0x54, 0x6c, 0xa7, 0xfb, 0xba, 0x94, 0x85,
	0xb7, 0xa5, 0x2c, 0xbc, 0x2f, 0x65, 0xe1, 0xe9, 0x43, 0xfe, 0x73, 0xdf, 0x9a, 0x58, 0x6c, 0xea,
	0x1b, 0xaa, 0x49, 0xe6, 0xda, 0x9a, 0xab, 0x75, 0xa2, 0x48, 0x4f, 0x22, 0x77, 0x36, 0xd1, 0x90,
	0x6b, 0x69, 0x41, 0xcb, 0xf8, 0xcf, 0x7f, 0x9e, 0xb3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b,
	0xd0, 0x1f, 0x9d, 0x94, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StateServiceClient is the client API for StateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateServiceClient interface {
	// Gets the current railway state
	GetRailwayState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RailwayState, error)
	// Enable the run mode of the process.
	EnableRunMode(ctx context.Context, in *EnableRunModeRequest, opts ...grpc.CallOption) (*RailwayState, error)
	// Disable the run mode of the process, switching back to edit mode.
	DisableRunMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RailwayState, error)
	// Fetch state changes when they happen
	GetStateChanges(ctx context.Context, in *GetStateChangesRequest, opts ...grpc.CallOption) (StateService_GetStateChangesClient, error)
	// Change the requested power state
	SetPower(ctx context.Context, in *SetPowerRequest, opts ...grpc.CallOption) (*RailwayState, error)
}

type stateServiceClient struct {
	cc *grpc.ClientConn
}

func NewStateServiceClient(cc *grpc.ClientConn) StateServiceClient {
	return &stateServiceClient{cc}
}

func (c *stateServiceClient) GetRailwayState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RailwayState, error) {
	out := new(RailwayState)
	err := c.cc.Invoke(ctx, "/binkyrailways.v1.StateService/GetRailwayState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) EnableRunMode(ctx context.Context, in *EnableRunModeRequest, opts ...grpc.CallOption) (*RailwayState, error) {
	out := new(RailwayState)
	err := c.cc.Invoke(ctx, "/binkyrailways.v1.StateService/EnableRunMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) DisableRunMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RailwayState, error) {
	out := new(RailwayState)
	err := c.cc.Invoke(ctx, "/binkyrailways.v1.StateService/DisableRunMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) GetStateChanges(ctx context.Context, in *GetStateChangesRequest, opts ...grpc.CallOption) (StateService_GetStateChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StateService_serviceDesc.Streams[0], "/binkyrailways.v1.StateService/GetStateChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &stateServiceGetStateChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StateService_GetStateChangesClient interface {
	Recv() (*StateChange, error)
	grpc.ClientStream
}

type stateServiceGetStateChangesClient struct {
	grpc.ClientStream
}

func (x *stateServiceGetStateChangesClient) Recv() (*StateChange, error) {
	m := new(StateChange)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stateServiceClient) SetPower(ctx context.Context, in *SetPowerRequest, opts ...grpc.CallOption) (*RailwayState, error) {
	out := new(RailwayState)
	err := c.cc.Invoke(ctx, "/binkyrailways.v1.StateService/SetPower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServiceServer is the server API for StateService service.
type StateServiceServer interface {
	// Gets the current railway state
	GetRailwayState(context.Context, *Empty) (*RailwayState, error)
	// Enable the run mode of the process.
	EnableRunMode(context.Context, *EnableRunModeRequest) (*RailwayState, error)
	// Disable the run mode of the process, switching back to edit mode.
	DisableRunMode(context.Context, *Empty) (*RailwayState, error)
	// Fetch state changes when they happen
	GetStateChanges(*GetStateChangesRequest, StateService_GetStateChangesServer) error
	// Change the requested power state
	SetPower(context.Context, *SetPowerRequest) (*RailwayState, error)
}

// UnimplementedStateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStateServiceServer struct {
}

func (*UnimplementedStateServiceServer) GetRailwayState(ctx context.Context, req *Empty) (*RailwayState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRailwayState not implemented")
}
func (*UnimplementedStateServiceServer) EnableRunMode(ctx context.Context, req *EnableRunModeRequest) (*RailwayState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableRunMode not implemented")
}
func (*UnimplementedStateServiceServer) DisableRunMode(ctx context.Context, req *Empty) (*RailwayState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableRunMode not implemented")
}
func (*UnimplementedStateServiceServer) GetStateChanges(req *GetStateChangesRequest, srv StateService_GetStateChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStateChanges not implemented")
}
func (*UnimplementedStateServiceServer) SetPower(ctx context.Context, req *SetPowerRequest) (*RailwayState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPower not implemented")
}

func RegisterStateServiceServer(s *grpc.Server, srv StateServiceServer) {
	s.RegisterService(&_StateService_serviceDesc, srv)
}

func _StateService_GetRailwayState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetRailwayState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/binkyrailways.v1.StateService/GetRailwayState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetRailwayState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_EnableRunMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRunModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).EnableRunMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/binkyrailways.v1.StateService/EnableRunMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).EnableRunMode(ctx, req.(*EnableRunModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_DisableRunMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).DisableRunMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/binkyrailways.v1.StateService/DisableRunMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).DisableRunMode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_GetStateChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStateChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateServiceServer).GetStateChanges(m, &stateServiceGetStateChangesServer{stream})
}

type StateService_GetStateChangesServer interface {
	Send(*StateChange) error
	grpc.ServerStream
}

type stateServiceGetStateChangesServer struct {
	grpc.ServerStream
}

func (x *stateServiceGetStateChangesServer) Send(m *StateChange) error {
	return x.ServerStream.SendMsg(m)
}

func _StateService_SetPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).SetPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/binkyrailways.v1.StateService/SetPower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).SetPower(ctx, req.(*SetPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "binkyrailways.v1.StateService",
	HandlerType: (*StateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRailwayState",
			Handler:    _StateService_GetRailwayState_Handler,
		},
		{
			MethodName: "EnableRunMode",
			Handler:    _StateService_EnableRunMode_Handler,
		},
		{
			MethodName: "DisableRunMode",
			Handler:    _StateService_DisableRunMode_Handler,
		},
		{
			MethodName: "SetPower",
			Handler:    _StateService_SetPower_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStateChanges",
			Handler:       _StateService_GetStateChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "br_state_service.proto",
}

func (m *EnableRunModeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnableRunModeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnableRunModeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Virtual {
		i--
		if m.Virtual {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetStateChangesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetStateChangesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetStateChangesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Bootstrap {
		i--
		if m.Bootstrap {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StateChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Loc != nil {
		{
			size, err := m.Loc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBrStateService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBrStateService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Railway != nil {
		{
			size, err := m.Railway.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBrStateService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SetPowerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetPowerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetPowerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBrStateService(dAtA []byte, offset int, v uint64) int {
	offset -= sovBrStateService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EnableRunModeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Virtual {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetStateChangesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Bootstrap {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StateChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Railway != nil {
		l = m.Railway.Size()
		n += 1 + l + sovBrStateService(uint64(l))
	}
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovBrStateService(uint64(l))
	}
	if m.Loc != nil {
		l = m.Loc.Size()
		n += 1 + l + sovBrStateService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SetPowerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBrStateService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBrStateService(x uint64) (n int) {
	return sovBrStateService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EnableRunModeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBrStateService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnableRunModeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnableRunModeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Virtual", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Virtual = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBrStateService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBrStateService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetStateChangesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBrStateService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetStateChangesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetStateChangesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bootstrap", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Bootstrap = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBrStateService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBrStateService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StateChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBrStateService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Railway", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBrStateService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBrStateService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Railway == nil {
				m.Railway = &RailwayState{}
			}
			if err := m.Railway.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBrStateService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBrStateService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &BlockState{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Loc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBrStateService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBrStateService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Loc == nil {
				m.Loc = &LocState{}
			}
			if err := m.Loc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBrStateService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBrStateService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetPowerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBrStateService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetPowerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetPowerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBrStateService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBrStateService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBrStateService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBrStateService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBrStateService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBrStateService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBrStateService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBrStateService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBrStateService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBrStateService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBrStateService = fmt.Errorf("proto: unexpected end of group")
)
